name: CI

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@release-1701263349990
        with:
          schema: "main:schema.graphql"
          approve-label: expected-breaking-change
